version: "3"

services:
  swagger-ui:
    image: charlesbases/swagger-ui:latest
    container_name: swagger-ui
    hostname: swagger_ui
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /opt/swagger:/swagger/api
    ports:
      - "${SWAGGER_POST:-8888}:8888"

networks:
  default:
    name: swagger
